job1:
  when: on_success
  script:
      - /opt/makeSite/nginxConf $CI_PROJECT_NAME pub $CI_BUILD_REPO;
  only:
      - master

job2:
  when: on_success
  script:
      - /opt/makeSite/nginxConf $CI_PROJECT_NAME dev $CI_BUILD_REPO;
  only:
      - develop
