<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Schedules extends Model
{
    public $fillable = [
        'type',
        'filename',
        'total_lines',
        'stopped_at',
        'running',
        'finished',
        'result_state',
        'result_message',
    ];

    public function getTypeNameAttribute()
    {
        $scheduleNames = config('app.schedulenames', []);

        return $scheduleNames[$this->type] ?? "Unknown Schedule";
    }

    public function getResultStateSwitchAttribute()
    {
        if ($this->finished) {
            return $this->result_state ? '<i class="fas fa-check text-success"></i>' : '<i class="fas fa-times text-danger"></i>';
        }

        $spinnerColor = $this->running ? "fa-spin" : "";

        return '<i class="fas fa-cog '.$spinnerColor.'"></i>';
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('created_at', 'desc');
        });
    }
}