<?php

namespace App\Plugins\Blog\Model;

use App\BaseModel;
use App\Plugins\Admin\Model\File;
use App\Plugins\Products\Model\Product;
use App\Plugins\Suppliers\Model\Supplier;
use Illuminate\Database\Eloquent\Builder;

class Blog extends BaseModel
{
    public $fillable = ['id', 'main_category', 'is_highlighted'];
    public $metaClass = __NAMESPACE__."\BlogMeta";

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('order', function (Builder $b) {
            return $b->orderBy('created_at', 'desc');
        });
    }

    public function extra_categories() {
        return $this->belongsToMany(BlogCategories::class);
    }

    public function main_category() {
        return $this->belongsTo(BlogCategories::class);
    }

    public function linked_products() {
        return $this->belongsToMany(Product::class);
    }

    public function linked_supplier() {
        return $this->belongsToMany(Supplier::class);
    }

    public function images() {
        return $this->hasMany(File::class, 'owner_id');
    }

    public function getBlogPictureAttribute()
    {
        return $this->images()->where("owner", "blog_picture")->get();
    }
}
